"use client";

import { useMemo, useState } from "react";

type Metric = { impressions: number | null; inflows: number | null; consultations: number | null; enrollments: number | null; spend: number | null };
type Totals = { impressions: number; inflows: number; consultations: number; enrollments: number; spend: number };
type Channel = { id: string; name: string; color: string; detail?: string };
const days = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"];
const channels: Channel[] = [
  { id: "daangn", name: "당근 광고", detail: "9월 신규 모집", color: "#e8852f" },
  { id: "blog", name: "네이버 블로그", color: "#39a36a" },
  { id: "instagram", name: "인스타그램", color: "#d86586" },
  { id: "event", name: "설명회 · 오프라인", color: "#8c68d8" },
  { id: "media", name: "제휴 · 미디어", color: "#4b91d1" },
];
const seed: Record<string, Metric> = {
  "daangn-8": { impressions: 3200, inflows: 42, consultations: 3, enrollments: 0, spend: 30000 },
  "blog-8": { impressions: 185, inflows: 9, consultations: 1, enrollments: 0, spend: null },
  "instagram-7": { impressions: 1240, inflows: 21, consultations: 0, enrollments: 0, spend: null },
  "event-10": { impressions: null, inflows: 12, consultations: 2, enrollments: 0, spend: 50000 },
};
const num = new Intl.NumberFormat("ko-KR");
const won = new Intl.NumberFormat("ko-KR", { style: "currency", currency: "KRW", maximumFractionDigits: 0 });

export default function Home() {
  const [records, setRecords] = useState(seed);
  const [selected, setSelected] = useState<{ channel: Channel; day: string } | null>(null);
  const [draft, setDraft] = useState<Metric | null>(null);
  const total = useMemo(() => Object.values(records).reduce<Totals>((a, b) => ({ impressions: a.impressions + (b.impressions ?? 0), inflows: a.inflows + (b.inflows ?? 0), consultations: a.consultations + (b.consultations ?? 0), enrollments: a.enrollments + (b.enrollments ?? 0), spend: a.spend + (b.spend ?? 0) }), { impressions: 0, inflows: 0, consultations: 0, enrollments: 0, spend: 0 }), [records]);
  const open = (channel: Channel, day: string) => { setSelected({ channel, day }); setDraft(records[`${channel.id}-${day}`] ?? { impressions: null, inflows: null, consultations: null, enrollments: null, spend: null }); };
  const save = () => { if (selected && draft) setRecords({ ...records, [`${selected.channel.id}-${selected.day}`]: draft }); setSelected(null); };
  return <main className="min-h-screen bg-[#f6f7f4] text-[#1c2720]">
    <header className="border-b border-[#e2e6df] bg-white px-6 py-5 lg:px-10"><div className="mx-auto flex max-w-[1560px] items-center justify-between"><div className="flex items-center gap-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#246b45] text-lg text-white">C</div><div><p className="text-sm font-semibold">채움영어학원 · 풍무캠퍼스</p><p className="text-xs text-[#728078]">마케팅 운영 시트</p></div></div><div className="flex gap-3"><span className="hidden rounded-full bg-[#edf7ef] px-3 py-2 text-xs text-[#297247] sm:inline">자동 저장됨</span><button className="rounded-lg border border-[#d8ded7] px-3 py-2 text-sm">PDF 보고서</button><button className="rounded-lg bg-[#246b45] px-3 py-2 text-sm text-white">+ 빠른 입력</button></div></div></header>
    <section className="mx-auto max-w-[1560px] px-6 py-7 lg:px-10"><div className="mb-7 flex items-end justify-between"><div><p className="mb-2 text-sm text-[#728078]">2026년 9월</p><h1 className="text-3xl font-semibold">이번 달 마케팅 현황</h1></div><div className="hidden gap-2 md:flex">{["전체", "광고", "콘텐츠", "이벤트"].map((x, i) => <button key={x} className={`rounded-full px-4 py-2 text-sm ${i === 0 ? "bg-[#1c2720] text-white" : "bg-white ring-1 ring-[#e1e6df]"}`}>{x}</button>)}</div></div>
      <div className="mb-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["노출", num.format(total.impressions), ""], ["유입", num.format(total.inflows), "#246b45"], ["상담", num.format(total.consultations), ""], ["등록", num.format(total.enrollments), ""], ["집행액", won.format(total.spend), "#c35b18"]].map(([label, value, color]) => <div key={label} className="rounded-xl border border-[#e0e5de] bg-white px-4 py-4"><p className="text-xs text-[#728078]">{label}</p><p className="mt-1 text-xl font-semibold" style={{ color }}>{value}</p></div>)}</div>
      <section className="overflow-hidden rounded-2xl border border-[#dfe5dd] bg-white"><div className="flex items-center justify-between border-b border-[#e7ebe5] px-5 py-4"><div className="flex gap-2"><button className="rounded-lg border border-[#dfe5dd] px-3 py-1.5 text-sm">‹ 8월</button><button className="rounded-lg bg-[#f2f5f1] px-3 py-1.5 text-sm font-medium">오늘 · 9월 8일</button><button className="rounded-lg border border-[#dfe5dd] px-3 py-1.5 text-sm">10월 ›</button></div><p className="text-xs text-[#728078]">날짜를 눌러 수치를 입력하세요</p></div><div className="overflow-x-auto"><div className="min-w-[1180px]"><div className="grid grid-cols-[220px_repeat(14,minmax(68px,1fr))] border-b border-[#e7ebe5] bg-[#fbfcfa]"><div className="sticky left-0 z-10 bg-[#fbfcfa] px-5 py-3 text-xs font-semibold text-[#728078]">채널 / 캠페인</div>{days.map((day) => <div key={day} className={`border-l border-[#edf0eb] px-2 py-3 text-center text-xs ${day === "8" ? "bg-[#eaf5ec] font-bold text-[#246b45]" : "text-[#728078]"}`}><p>{day}</p><p className="text-[10px] font-normal">{["일", "월", "화", "수", "목", "금", "토"][Number(day) % 7]}</p></div>)}</div>{channels.map((channel) => <div key={channel.id} className="grid grid-cols-[220px_repeat(14,minmax(68px,1fr))] border-b border-[#edf0eb] last:border-b-0"><div className="sticky left-0 z-10 flex min-h-[102px] flex-col justify-center bg-white px-5"><div className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: channel.color }} /><span className="font-semibold">{channel.name}</span></div>{channel.detail && <span className="mt-1 pl-[18px] text-xs text-[#849087]">{channel.detail}</span>}</div>{days.map((day) => <Cell key={day} metric={records[`${channel.id}-${day}`]} current={day === "8"} onClick={() => open(channel, day)} />)}</div>)}</div></div></section>
    </section>{selected && draft && <Editor selected={selected} draft={draft} setDraft={setDraft} save={save} close={() => setSelected(null)} />}</main>;
}
function Cell({ metric, current, onClick }: { metric?: Metric; current: boolean; onClick: () => void }) { const yes = metric && Object.values(metric).some((x) => x !== null); return <button onClick={onClick} className={`min-h-[102px] border-l border-[#edf0eb] p-2 text-left hover:bg-[#f2f8f2] ${current ? "bg-[#f8fcf8]" : ""}`}>{yes ? <div className="space-y-1 text-[10px] text-[#4d5c53]"><p>노출 <b className="float-right text-[#1c2720]">{num.format(metric.impressions ?? 0)}</b></p><p>유입 <b className="float-right text-[#1c2720]">{metric.inflows ?? 0}</b></p><p>상담 <b className="float-right text-[#1c2720]">{metric.consultations ?? 0}</b></p><p className="border-t border-[#e6ece5] pt-1 text-[#c35b18]">{metric.spend ? won.format(metric.spend) : "비용 없음"}</p></div> : <div className="grid h-full place-items-center text-lg text-[#cbd4cb]">+</div>}</button>; }
function Editor({ selected, draft, setDraft, save, close }: { selected: { channel: Channel; day: string }; draft: Metric; setDraft: (value: Metric) => void; save: () => void; close: () => void }) { const fields: Array<[keyof Metric, string, string]> = [["impressions", "노출", "명"], ["inflows", "유입", "명"], ["consultations", "상담", "건"], ["enrollments", "등록", "명"], ["spend", "집행액", "원"]]; return <div className="fixed inset-0 z-20 flex justify-end bg-[#172219]/20" onMouseDown={close}><aside onMouseDown={(e) => e.stopPropagation()} className="h-full w-full max-w-md bg-white p-8 shadow-2xl"><div className="flex justify-between"><div><p className="text-sm text-[#728078]">9월 {selected.day}일</p><h2 className="mt-1 text-2xl font-semibold">{selected.channel.name}</h2></div><button onClick={close} className="text-xl text-[#728078]">×</button></div><div className="mt-8 space-y-4">{fields.map(([key, label, unit]) => <label key={key} className="block"><span className="mb-1.5 block text-sm font-medium">{label}</span><div className="flex rounded-lg border border-[#d9e1d8]"><input type="number" min="0" value={draft[key] ?? ""} onChange={(e) => setDraft({ ...draft, [key]: e.target.value === "" ? null : Number(e.target.value) })} className="w-full px-3 py-2.5 outline-none" placeholder="미입력" /><span className="flex items-center pr-3 text-sm text-[#728078]">{unit}</span></div></label>)}</div><label className="mt-5 block"><span className="mb-1.5 block text-sm font-medium">메모</span><textarea className="min-h-24 w-full rounded-lg border border-[#d9e1d8] p-3 text-sm" placeholder="콘텐츠, 이벤트, 특이사항" /></label><div className="mt-7 flex gap-3"><button onClick={close} className="flex-1 rounded-lg border border-[#d9e1d8] py-3">취소</button><button onClick={save} className="flex-1 rounded-lg bg-[#246b45] py-3 font-semibold text-white">저장</button></div></aside></div>; }
